# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d8f27fe12b45def4e82f975f4a07d33ac3aa6987b16944c8486ef6c220c6e8929524a58c236c2c96767aebb0c3246c1c7584d3cd66e74e973c9fa1aa8fd34334

test:
  secret_key_base: 8e69daf25b3c8620a80afb92f790d0c8e0e944c9c23f73a05b079b98a5251b0b4db6e7aedc107655be8a932456b37cc6d35ac19a518f0d969ab61eb68afcdf2d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
